// Generated by scripts/optimize-hero.mjs. Static imports give these files immutable cache URLs.
import frame1_640_avif from "../../public/images/hero-optimized/hero-1-640.avif";
import frame1_640_webp from "../../public/images/hero-optimized/hero-1-640.webp";
import frame1_852_avif from "../../public/images/hero-optimized/hero-1-852.avif";
import frame1_852_webp from "../../public/images/hero-optimized/hero-1-852.webp";
import frame2_640_avif from "../../public/images/hero-optimized/hero-2-640.avif";
import frame2_640_webp from "../../public/images/hero-optimized/hero-2-640.webp";
import frame2_852_avif from "../../public/images/hero-optimized/hero-2-852.avif";
import frame2_852_webp from "../../public/images/hero-optimized/hero-2-852.webp";
import frame3_640_avif from "../../public/images/hero-optimized/hero-3-640.avif";
import frame3_640_webp from "../../public/images/hero-optimized/hero-3-640.webp";
import frame3_852_avif from "../../public/images/hero-optimized/hero-3-852.avif";
import frame3_852_webp from "../../public/images/hero-optimized/hero-3-852.webp";
import frame4_640_avif from "../../public/images/hero-optimized/hero-4-640.avif";
import frame4_640_webp from "../../public/images/hero-optimized/hero-4-640.webp";
import frame4_852_avif from "../../public/images/hero-optimized/hero-4-852.avif";
import frame4_852_webp from "../../public/images/hero-optimized/hero-4-852.webp";
import frame5_640_avif from "../../public/images/hero-optimized/hero-5-640.avif";
import frame5_640_webp from "../../public/images/hero-optimized/hero-5-640.webp";
import frame5_851_avif from "../../public/images/hero-optimized/hero-5-851.avif";
import frame5_851_webp from "../../public/images/hero-optimized/hero-5-851.webp";

export const mobileHeroImages = [
  {
    src: frame1_852_webp.src,
    width: frame1_852_webp.width,
    height: frame1_852_webp.height,
    avif: `${frame1_640_avif.src} 640w, ${frame1_852_avif.src} 852w`,
    webp: `${frame1_640_webp.src} 640w, ${frame1_852_webp.src} 852w`,
  },
  {
    src: frame2_852_webp.src,
    width: frame2_852_webp.width,
    height: frame2_852_webp.height,
    avif: `${frame2_640_avif.src} 640w, ${frame2_852_avif.src} 852w`,
    webp: `${frame2_640_webp.src} 640w, ${frame2_852_webp.src} 852w`,
  },
  {
    src: frame3_852_webp.src,
    width: frame3_852_webp.width,
    height: frame3_852_webp.height,
    avif: `${frame3_640_avif.src} 640w, ${frame3_852_avif.src} 852w`,
    webp: `${frame3_640_webp.src} 640w, ${frame3_852_webp.src} 852w`,
  },
  {
    src: frame4_852_webp.src,
    width: frame4_852_webp.width,
    height: frame4_852_webp.height,
    avif: `${frame4_640_avif.src} 640w, ${frame4_852_avif.src} 852w`,
    webp: `${frame4_640_webp.src} 640w, ${frame4_852_webp.src} 852w`,
  },
  {
    src: frame5_851_webp.src,
    width: frame5_851_webp.width,
    height: frame5_851_webp.height,
    avif: `${frame5_640_avif.src} 640w, ${frame5_851_avif.src} 851w`,
    webp: `${frame5_640_webp.src} 640w, ${frame5_851_webp.src} 851w`,
  }
];
