import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";

// Preserve the original framing and files. Generate once, not on each CDN miss.
const directory = "public/images/hero-optimized";
await mkdir(directory, { recursive: true });
const imports = [];
const frames = [];
for (let frame = 1; frame <= 5; frame++) {
  const source = `public/images/hero-mobile-bg${frame === 1 ? "" : `-${frame}`}.webp`;
  const { width: originalWidth } = await sharp(source).metadata();
  const widths = [640, originalWidth];
  for (const width of widths) {
    for (const format of ["avif", "webp"]) {
      const name = `hero-${frame}-${width}.${format}`;
      const info = await sharp(source)
        .resize({ width, withoutEnlargement: true })
        .toFormat(format, { quality: format === "avif" ? 55 : 78, effort: 6 })
        .toFile(`${directory}/${name}`);
      imports.push(`import frame${frame}_${width}_${format} from "../../public/images/hero-optimized/${name}";`);
      console.log(`${name}: ${info.size} bytes`);
    }
  }
  const base = `frame${frame}_${originalWidth}_webp`;
  frames.push(`  {
    src: ${base}.src,
    width: ${base}.width,
    height: ${base}.height,
    avif: \`${widths.map(w => `\${frame${frame}_${w}_avif.src} ${w}w`).join(", ")}\`,
    webp: \`${widths.map(w => `\${frame${frame}_${w}_webp.src} ${w}w`).join(", ")}\`,
  }`);
}
await writeFile("src/config/mobileHeroImages.ts", `// Generated by scripts/optimize-hero.mjs. Static imports give these files immutable cache URLs.
${imports.join("\n")}

export const mobileHeroImages = [
${frames.join(",\n")}
];
`);
